version: '2.2'
services:
  elasticsearch:
    build: 
      context: .
      dockerfile: Dockerfile-elastic
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - data-es:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./certs/elastic-certificates.p12:/usr/share/elasticsearch/config/certificates/elastic-certificates.p12

volumes:
  data-es:
